### ISSUE TITLE
CC0 recommendation not ideal

### ISSUE THREAD

**Issue by hannob** [david-a-wheeler/spdx-tutorial#14]
The recommendation in
https://github.com/david-a-wheeler/spdx-tutorial/
regarding CC0 may not be ideal.

A few concerns have been raised about CC0, and it is not accepted by everyone as a FOSS license, see e.g.:
https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/

Also, the quote from the FSF is no longer accurate, the FSF now writes: "For works of software it is not recommended, as CC0 has a term expressly stating it does not grant you any patent licenses.", see https://www.gnu.org/licenses/license-list.html#CC0

By now, I believe 0BSD is the "most acceptable" de-facto public domain license, it's OSI approved. I use it for some of my personal projects and am trying to convert existing CC0 projects to it.

**Comment by david-a-wheeler** [comment]
Great point. I'll modify it.

**Comment by david-a-wheeler** [comment]
I think MIT is the better choice, as it's more common, but I'll certainly note 0BSD as an alternative.

**Comment by david-a-wheeler** [comment]
Thanks so much! I merged a change that I *think* fixes it. If you see any more problems, please create an issue or pull request.

**Comment by hannob** [comment]
I'm not entirely happy with the change, you are mostly recommending licenses of a different kind as an alternative to CC0.

When people choose CC0, what they usually want to express is essentially "I want my code to be usable without any restrictions", or "Public-Domain-alike" license. MIT is a "permissive with attribution"-type license, as are many others.

I'll do a short PR with a proposed change.

(From what I could gather, 0BSD is the most acceptable "permissive *without* attribution". CC0 has the patent thing, people have concerns that Unlicense/WTFPL aren't proper legal speak - I think there are some projects and/or companies that won't accept them as FOSS licenses, 0BSD is "ISC without attribution requirement", and OSI-approved.)
