### ISSUE TITLE
CC0 for software

### ISSUE THREAD

**Issue by spatil47** [david-a-wheeler/spdx-tutorial#3]
CC0 has been recommended by the Free Software Foundation as an acceptable license for releasing software into the public domain. The legal text of the CC0 dedication _does_ include a disclaimer of warranty in section 4b:

> Affirmer offers the Work as-is and makes no representations or warranties of any kind concerning the Work, express, implied, statutory or otherwise, including without limitation warranties of title, merchantability, fitness for a particular purpose, non infringement, or the absence of latent or other defects, accuracy, or the present or absence of errors, whether or not discoverable, all to the greatest extent permissible under applicable law.

**Comment by david-a-wheeler** [comment]
Thanks!  You're absolutely right, my mistake.  My intended point was subtler: CC0 doesn't say "You may not hold me liable" as a condition of the license, because there are no conditions.  But the text in the document is wrong.  I will fix it.

**Comment by david-a-wheeler** [comment]
I've updated the text in a way that I *hope* makes it better.  Thanks for the report.
