### ISSUE TITLE
Reference SPDX v2.1

### ISSUE THREAD

**Issue by znerd** [david-a-wheeler/spdx-tutorial#6]
Currently the document refers to SPDX 2.0, with a link to:
- https://spdx.org/SPDX-specifications/spdx-version-2.0

…but the latest release version appears to be 2.1. Hence it seems appropriate to reflect that by referencing the latter.

**Comment by david-a-wheeler** [comment]
Good point. I'll change things to link the page https://spdx.org/specifications so that it'll always stay current.

**Comment by david-a-wheeler** [comment]
Done with commit db78e71c21895b92f469a7b47351c150d1743056
